steps:
  - label: 'Build packages'
    command: './script/build'
    artifact_paths: bin/**/*
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: cli

  - wait

  - label: ":mag:"
    command: "./script/extract-cli-version"
    env:
      CALIBRE_API_KEY: noop

  - wait

  - name: ":s3: publish binaries"
    command: "scripts/publish"
    branches: "master"
